application: torrelaymonitoring
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /status
  script: status.status
- url: /.*
  script: app.app

libraries:
- name: ssl
  version: latest
